print ("Hello there")
income = int(input("enter your monthly income:"))
expense_A = int(input(("enter your expenses A:")))
expense_B= int(input(("enter your expenses B:")))
expense_C = int(input(("enter your expenses C:")))
expense_D = int(input(("enter your expenses D:")))
expense_E= float(input(("enter your expenses E:")))
total_expenses = (expense_A + expense_B + expense_C + expense_D + expense_E)
print(f"Your Total expense is: {total_expenses}")
savings = float(income-total_expenses)
print(f"Your savings are:{savings} ")
savings_percentage = ((savings/income)*10)
print(f"percentage of money saved: {savings_percentage}" + "%")
